// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: enforcer.proto

package enforcerapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Enforcer_RegisterContainer_FullMethodName     = "/agentcontainers.enforcer.v1.Enforcer/RegisterContainer"
	Enforcer_UnregisterContainer_FullMethodName   = "/agentcontainers.enforcer.v1.Enforcer/UnregisterContainer"
	Enforcer_PrepareToolCall_FullMethodName       = "/agentcontainers.enforcer.v1.Enforcer/PrepareToolCall"
	Enforcer_CompleteToolCall_FullMethodName      = "/agentcontainers.enforcer.v1.Enforcer/CompleteToolCall"
	Enforcer_ApplyNetworkPolicy_FullMethodName    = "/agentcontainers.enforcer.v1.Enforcer/ApplyNetworkPolicy"
	Enforcer_ApplyFilesystemPolicy_FullMethodName = "/agentcontainers.enforcer.v1.Enforcer/ApplyFilesystemPolicy"
	Enforcer_ApplyProcessPolicy_FullMethodName    = "/agentcontainers.enforcer.v1.Enforcer/ApplyProcessPolicy"
	Enforcer_ApplyCredentialPolicy_FullMethodName = "/agentcontainers.enforcer.v1.Enforcer/ApplyCredentialPolicy"
	Enforcer_InjectSecrets_FullMethodName         = "/agentcontainers.enforcer.v1.Enforcer/InjectSecrets"
	Enforcer_LoadPolicyBundle_FullMethodName      = "/agentcontainers.enforcer.v1.Enforcer/LoadPolicyBundle"
	Enforcer_StreamEvents_FullMethodName          = "/agentcontainers.enforcer.v1.Enforcer/StreamEvents"
	Enforcer_GetStats_FullMethodName              = "/agentcontainers.enforcer.v1.Enforcer/GetStats"
	Enforcer_LoadComponent_FullMethodName         = "/agentcontainers.enforcer.v1.Enforcer/LoadComponent"
	Enforcer_UnloadComponent_FullMethodName       = "/agentcontainers.enforcer.v1.Enforcer/UnloadComponent"
	Enforcer_ListComponents_FullMethodName        = "/agentcontainers.enforcer.v1.Enforcer/ListComponents"
	Enforcer_ListTools_FullMethodName             = "/agentcontainers.enforcer.v1.Enforcer/ListTools"
	Enforcer_CallTool_FullMethodName              = "/agentcontainers.enforcer.v1.Enforcer/CallTool"
)

// EnforcerClient is the client API for Enforcer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnforcerClient interface {
	// Container lifecycle — register/unregister cgroups for enforcement.
	RegisterContainer(ctx context.Context, in *RegisterContainerRequest, opts ...grpc.CallOption) (*RegisterContainerResponse, error)
	UnregisterContainer(ctx context.Context, in *UnregisterContainerRequest, opts ...grpc.CallOption) (*UnregisterContainerResponse, error)
	PrepareToolCall(ctx context.Context, in *PrepareToolCallRequest, opts ...grpc.CallOption) (*PrepareToolCallResponse, error)
	CompleteToolCall(ctx context.Context, in *CompleteToolCallRequest, opts ...grpc.CallOption) (*CompleteToolCallResponse, error)
	// Per-boundary-class policy application.
	ApplyNetworkPolicy(ctx context.Context, in *NetworkPolicyRequest, opts ...grpc.CallOption) (*PolicyResponse, error)
	ApplyFilesystemPolicy(ctx context.Context, in *FilesystemPolicyRequest, opts ...grpc.CallOption) (*PolicyResponse, error)
	ApplyProcessPolicy(ctx context.Context, in *ProcessPolicyRequest, opts ...grpc.CallOption) (*PolicyResponse, error)
	ApplyCredentialPolicy(ctx context.Context, in *CredentialPolicyRequest, opts ...grpc.CallOption) (*PolicyResponse, error)
	InjectSecrets(ctx context.Context, in *InjectSecretsRequest, opts ...grpc.CallOption) (*InjectSecretsResponse, error)
	// Policy bundle — content trust for ACL re-derivation.
	// Must be called before ApplyCredentialPolicy.  The enforcer stores a hash
	// of the policy JSON so that subsequent ApplyCredentialPolicy calls can be
	// verified against the signed policy.
	LoadPolicyBundle(ctx context.Context, in *LoadPolicyBundleRequest, opts ...grpc.CallOption) (*LoadPolicyBundleResponse, error)
	// Observability.
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EnforcementEvent], error)
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// WASM Component lifecycle.
	LoadComponent(ctx context.Context, in *LoadComponentRequest, opts ...grpc.CallOption) (*LoadComponentResponse, error)
	UnloadComponent(ctx context.Context, in *UnloadComponentRequest, opts ...grpc.CallOption) (*UnloadComponentResponse, error)
	ListComponents(ctx context.Context, in *ListComponentsRequest, opts ...grpc.CallOption) (*ListComponentsResponse, error)
	// Tool invocation.
	ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error)
	CallTool(ctx context.Context, in *CallToolRequest, opts ...grpc.CallOption) (*CallToolResponse, error)
}

type enforcerClient struct {
	cc grpc.ClientConnInterface
}

func NewEnforcerClient(cc grpc.ClientConnInterface) EnforcerClient {
	return &enforcerClient{cc}
}

func (c *enforcerClient) RegisterContainer(ctx context.Context, in *RegisterContainerRequest, opts ...grpc.CallOption) (*RegisterContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterContainerResponse)
	err := c.cc.Invoke(ctx, Enforcer_RegisterContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enforcerClient) UnregisterContainer(ctx context.Context, in *UnregisterContainerRequest, opts ...grpc.CallOption) (*UnregisterContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterContainerResponse)
	err := c.cc.Invoke(ctx, Enforcer_UnregisterContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enforcerClient) PrepareToolCall(ctx context.Context, in *PrepareToolCallRequest, opts ...grpc.CallOption) (*PrepareToolCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareToolCallResponse)
	err := c.cc.Invoke(ctx, Enforcer_PrepareToolCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enforcerClient) CompleteToolCall(ctx context.Context, in *CompleteToolCallRequest, opts ...grpc.CallOption) (*CompleteToolCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteToolCallResponse)
	err := c.cc.Invoke(ctx, Enforcer_CompleteToolCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enforcerClient) ApplyNetworkPolicy(ctx context.Context, in *NetworkPolicyRequest, opts ...grpc.CallOption) (*PolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyResponse)
	err := c.cc.Invoke(ctx, Enforcer_ApplyNetworkPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enforcerClient) ApplyFilesystemPolicy(ctx context.Context, in *FilesystemPolicyRequest, opts ...grpc.CallOption) (*PolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyResponse)
	err := c.cc.Invoke(ctx, Enforcer_ApplyFilesystemPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enforcerClient) ApplyProcessPolicy(ctx context.Context, in *ProcessPolicyRequest, opts ...grpc.CallOption) (*PolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyResponse)
	err := c.cc.Invoke(ctx, Enforcer_ApplyProcessPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enforcerClient) ApplyCredentialPolicy(ctx context.Context, in *CredentialPolicyRequest, opts ...grpc.CallOption) (*PolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyResponse)
	err := c.cc.Invoke(ctx, Enforcer_ApplyCredentialPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enforcerClient) InjectSecrets(ctx context.Context, in *InjectSecretsRequest, opts ...grpc.CallOption) (*InjectSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InjectSecretsResponse)
	err := c.cc.Invoke(ctx, Enforcer_InjectSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enforcerClient) LoadPolicyBundle(ctx context.Context, in *LoadPolicyBundleRequest, opts ...grpc.CallOption) (*LoadPolicyBundleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadPolicyBundleResponse)
	err := c.cc.Invoke(ctx, Enforcer_LoadPolicyBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enforcerClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EnforcementEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Enforcer_ServiceDesc.Streams[0], Enforcer_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, EnforcementEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Enforcer_StreamEventsClient = grpc.ServerStreamingClient[EnforcementEvent]

func (c *enforcerClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, Enforcer_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enforcerClient) LoadComponent(ctx context.Context, in *LoadComponentRequest, opts ...grpc.CallOption) (*LoadComponentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadComponentResponse)
	err := c.cc.Invoke(ctx, Enforcer_LoadComponent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enforcerClient) UnloadComponent(ctx context.Context, in *UnloadComponentRequest, opts ...grpc.CallOption) (*UnloadComponentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnloadComponentResponse)
	err := c.cc.Invoke(ctx, Enforcer_UnloadComponent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enforcerClient) ListComponents(ctx context.Context, in *ListComponentsRequest, opts ...grpc.CallOption) (*ListComponentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListComponentsResponse)
	err := c.cc.Invoke(ctx, Enforcer_ListComponents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enforcerClient) ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListToolsResponse)
	err := c.cc.Invoke(ctx, Enforcer_ListTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enforcerClient) CallTool(ctx context.Context, in *CallToolRequest, opts ...grpc.CallOption) (*CallToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallToolResponse)
	err := c.cc.Invoke(ctx, Enforcer_CallTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnforcerServer is the server API for Enforcer service.
// All implementations must embed UnimplementedEnforcerServer
// for forward compatibility.
type EnforcerServer interface {
	// Container lifecycle — register/unregister cgroups for enforcement.
	RegisterContainer(context.Context, *RegisterContainerRequest) (*RegisterContainerResponse, error)
	UnregisterContainer(context.Context, *UnregisterContainerRequest) (*UnregisterContainerResponse, error)
	PrepareToolCall(context.Context, *PrepareToolCallRequest) (*PrepareToolCallResponse, error)
	CompleteToolCall(context.Context, *CompleteToolCallRequest) (*CompleteToolCallResponse, error)
	// Per-boundary-class policy application.
	ApplyNetworkPolicy(context.Context, *NetworkPolicyRequest) (*PolicyResponse, error)
	ApplyFilesystemPolicy(context.Context, *FilesystemPolicyRequest) (*PolicyResponse, error)
	ApplyProcessPolicy(context.Context, *ProcessPolicyRequest) (*PolicyResponse, error)
	ApplyCredentialPolicy(context.Context, *CredentialPolicyRequest) (*PolicyResponse, error)
	InjectSecrets(context.Context, *InjectSecretsRequest) (*InjectSecretsResponse, error)
	// Policy bundle — content trust for ACL re-derivation.
	// Must be called before ApplyCredentialPolicy.  The enforcer stores a hash
	// of the policy JSON so that subsequent ApplyCredentialPolicy calls can be
	// verified against the signed policy.
	LoadPolicyBundle(context.Context, *LoadPolicyBundleRequest) (*LoadPolicyBundleResponse, error)
	// Observability.
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[EnforcementEvent]) error
	GetStats(context.Context, *GetStatsRequest) (*StatsResponse, error)
	// WASM Component lifecycle.
	LoadComponent(context.Context, *LoadComponentRequest) (*LoadComponentResponse, error)
	UnloadComponent(context.Context, *UnloadComponentRequest) (*UnloadComponentResponse, error)
	ListComponents(context.Context, *ListComponentsRequest) (*ListComponentsResponse, error)
	// Tool invocation.
	ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error)
	CallTool(context.Context, *CallToolRequest) (*CallToolResponse, error)
	mustEmbedUnimplementedEnforcerServer()
}

// UnimplementedEnforcerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnforcerServer struct{}

func (UnimplementedEnforcerServer) RegisterContainer(context.Context, *RegisterContainerRequest) (*RegisterContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterContainer not implemented")
}
func (UnimplementedEnforcerServer) UnregisterContainer(context.Context, *UnregisterContainerRequest) (*UnregisterContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterContainer not implemented")
}
func (UnimplementedEnforcerServer) PrepareToolCall(context.Context, *PrepareToolCallRequest) (*PrepareToolCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareToolCall not implemented")
}
func (UnimplementedEnforcerServer) CompleteToolCall(context.Context, *CompleteToolCallRequest) (*CompleteToolCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteToolCall not implemented")
}
func (UnimplementedEnforcerServer) ApplyNetworkPolicy(context.Context, *NetworkPolicyRequest) (*PolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyNetworkPolicy not implemented")
}
func (UnimplementedEnforcerServer) ApplyFilesystemPolicy(context.Context, *FilesystemPolicyRequest) (*PolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyFilesystemPolicy not implemented")
}
func (UnimplementedEnforcerServer) ApplyProcessPolicy(context.Context, *ProcessPolicyRequest) (*PolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyProcessPolicy not implemented")
}
func (UnimplementedEnforcerServer) ApplyCredentialPolicy(context.Context, *CredentialPolicyRequest) (*PolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyCredentialPolicy not implemented")
}
func (UnimplementedEnforcerServer) InjectSecrets(context.Context, *InjectSecretsRequest) (*InjectSecretsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InjectSecrets not implemented")
}
func (UnimplementedEnforcerServer) LoadPolicyBundle(context.Context, *LoadPolicyBundleRequest) (*LoadPolicyBundleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadPolicyBundle not implemented")
}
func (UnimplementedEnforcerServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[EnforcementEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedEnforcerServer) GetStats(context.Context, *GetStatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedEnforcerServer) LoadComponent(context.Context, *LoadComponentRequest) (*LoadComponentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadComponent not implemented")
}
func (UnimplementedEnforcerServer) UnloadComponent(context.Context, *UnloadComponentRequest) (*UnloadComponentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnloadComponent not implemented")
}
func (UnimplementedEnforcerServer) ListComponents(context.Context, *ListComponentsRequest) (*ListComponentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListComponents not implemented")
}
func (UnimplementedEnforcerServer) ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedEnforcerServer) CallTool(context.Context, *CallToolRequest) (*CallToolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallTool not implemented")
}
func (UnimplementedEnforcerServer) mustEmbedUnimplementedEnforcerServer() {}
func (UnimplementedEnforcerServer) testEmbeddedByValue()                  {}

// UnsafeEnforcerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnforcerServer will
// result in compilation errors.
type UnsafeEnforcerServer interface {
	mustEmbedUnimplementedEnforcerServer()
}

func RegisterEnforcerServer(s grpc.ServiceRegistrar, srv EnforcerServer) {
	// If the following call pancis, it indicates UnimplementedEnforcerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Enforcer_ServiceDesc, srv)
}

func _Enforcer_RegisterContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnforcerServer).RegisterContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enforcer_RegisterContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnforcerServer).RegisterContainer(ctx, req.(*RegisterContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Enforcer_UnregisterContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnforcerServer).UnregisterContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enforcer_UnregisterContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnforcerServer).UnregisterContainer(ctx, req.(*UnregisterContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Enforcer_PrepareToolCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareToolCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnforcerServer).PrepareToolCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enforcer_PrepareToolCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnforcerServer).PrepareToolCall(ctx, req.(*PrepareToolCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Enforcer_CompleteToolCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteToolCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnforcerServer).CompleteToolCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enforcer_CompleteToolCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnforcerServer).CompleteToolCall(ctx, req.(*CompleteToolCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Enforcer_ApplyNetworkPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnforcerServer).ApplyNetworkPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enforcer_ApplyNetworkPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnforcerServer).ApplyNetworkPolicy(ctx, req.(*NetworkPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Enforcer_ApplyFilesystemPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilesystemPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnforcerServer).ApplyFilesystemPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enforcer_ApplyFilesystemPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnforcerServer).ApplyFilesystemPolicy(ctx, req.(*FilesystemPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Enforcer_ApplyProcessPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnforcerServer).ApplyProcessPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enforcer_ApplyProcessPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnforcerServer).ApplyProcessPolicy(ctx, req.(*ProcessPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Enforcer_ApplyCredentialPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnforcerServer).ApplyCredentialPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enforcer_ApplyCredentialPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnforcerServer).ApplyCredentialPolicy(ctx, req.(*CredentialPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Enforcer_InjectSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InjectSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnforcerServer).InjectSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enforcer_InjectSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnforcerServer).InjectSecrets(ctx, req.(*InjectSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Enforcer_LoadPolicyBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadPolicyBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnforcerServer).LoadPolicyBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enforcer_LoadPolicyBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnforcerServer).LoadPolicyBundle(ctx, req.(*LoadPolicyBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Enforcer_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EnforcerServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, EnforcementEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Enforcer_StreamEventsServer = grpc.ServerStreamingServer[EnforcementEvent]

func _Enforcer_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnforcerServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enforcer_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnforcerServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Enforcer_LoadComponent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadComponentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnforcerServer).LoadComponent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enforcer_LoadComponent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnforcerServer).LoadComponent(ctx, req.(*LoadComponentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Enforcer_UnloadComponent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadComponentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnforcerServer).UnloadComponent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enforcer_UnloadComponent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnforcerServer).UnloadComponent(ctx, req.(*UnloadComponentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Enforcer_ListComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListComponentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnforcerServer).ListComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enforcer_ListComponents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnforcerServer).ListComponents(ctx, req.(*ListComponentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Enforcer_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnforcerServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enforcer_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnforcerServer).ListTools(ctx, req.(*ListToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Enforcer_CallTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnforcerServer).CallTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enforcer_CallTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnforcerServer).CallTool(ctx, req.(*CallToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Enforcer_ServiceDesc is the grpc.ServiceDesc for Enforcer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Enforcer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentcontainers.enforcer.v1.Enforcer",
	HandlerType: (*EnforcerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterContainer",
			Handler:    _Enforcer_RegisterContainer_Handler,
		},
		{
			MethodName: "UnregisterContainer",
			Handler:    _Enforcer_UnregisterContainer_Handler,
		},
		{
			MethodName: "PrepareToolCall",
			Handler:    _Enforcer_PrepareToolCall_Handler,
		},
		{
			MethodName: "CompleteToolCall",
			Handler:    _Enforcer_CompleteToolCall_Handler,
		},
		{
			MethodName: "ApplyNetworkPolicy",
			Handler:    _Enforcer_ApplyNetworkPolicy_Handler,
		},
		{
			MethodName: "ApplyFilesystemPolicy",
			Handler:    _Enforcer_ApplyFilesystemPolicy_Handler,
		},
		{
			MethodName: "ApplyProcessPolicy",
			Handler:    _Enforcer_ApplyProcessPolicy_Handler,
		},
		{
			MethodName: "ApplyCredentialPolicy",
			Handler:    _Enforcer_ApplyCredentialPolicy_Handler,
		},
		{
			MethodName: "InjectSecrets",
			Handler:    _Enforcer_InjectSecrets_Handler,
		},
		{
			MethodName: "LoadPolicyBundle",
			Handler:    _Enforcer_LoadPolicyBundle_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _Enforcer_GetStats_Handler,
		},
		{
			MethodName: "LoadComponent",
			Handler:    _Enforcer_LoadComponent_Handler,
		},
		{
			MethodName: "UnloadComponent",
			Handler:    _Enforcer_UnloadComponent_Handler,
		},
		{
			MethodName: "ListComponents",
			Handler:    _Enforcer_ListComponents_Handler,
		},
		{
			MethodName: "ListTools",
			Handler:    _Enforcer_ListTools_Handler,
		},
		{
			MethodName: "CallTool",
			Handler:    _Enforcer_CallTool_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _Enforcer_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "enforcer.proto",
}
